#ifndef RN_REVMAP_H
#define RN_REVMAP_H

#include "ps2_runtime.h"

/* The port's address map, reversed: a target address back to its reference one.
 *
 * The map itself is per-build data generated by tools/gen_revmap.py and compiled in
 * as rn_revmap[].  Only the interval start and the delta are stored: the interval
 * ends where the next one starts, and the reference address is target - delta, so
 * keeping either of those as well would double the table for nothing.  Two words per
 * interval across ~25000 intervals is 200 KB of the executable.
 *
 * An address outside the table has no known reference address, and lookups return it
 * unchanged.  That is deliberate rather than a fallback: it also makes the function
 * correct on the build the tables were written for, where nothing moves and the
 * answer is the input. */
typedef struct {
    u32 target;      /* first target address of the interval */
    u32 delta;       /* target - reference, so reference = target - delta */
} rn_revmap_entry;

extern const rn_revmap_entry rn_revmap[];
extern const unsigned rn_revmap_count;

/* The reference address for `a`, or `a` itself when the map does not cover it. */
u32 rn_revmap_to_us(u32 a);

#endif
